import { db } from '../../prisma/db';
import type { FieldOutputTypes } from '../../prisma/contract.d';
import { NotFoundError } from '../../shared/errors';
import { buildMeta, type PaginationParams } from '../../shared/pagination';
import { getGoodsReceiptById } from './goods-receipt.service';

type InvoiceRow = FieldOutputTypes['public']['Invoice'];

/** Read-only in this MVP pass — invoices are always auto-generated by `createGoodsReceipt`. */
export async function listInvoices(companyId: string, pagination: PaginationParams) {
  const companySuppliers = await db.orm.public.Supplier.where((s) => s.companyId.eq(companyId)).select('id').all();
  const supplierIds = companySuppliers.map((s) => s.id);

  if (supplierIds.length === 0) {
    return { items: [], meta: buildMeta(pagination, 0) };
  }

  const receipts = await db.orm.public.GoodsReceipt.where((gr) => gr.supplierId.in(supplierIds)).select('id').all();
  const receiptIds = receipts.map((r) => r.id);

  if (receiptIds.length === 0) {
    return { items: [], meta: buildMeta(pagination, 0) };
  }

  const [items, { total }] = await Promise.all([
    db.orm.public.Invoice
      .where((inv) => inv.goodsReceiptId.in(receiptIds))
      .orderBy((inv) => inv.createdAt.desc())
      .offset(pagination.skip)
      .limit(pagination.take)
      .all(),
    db.orm.public.Invoice.where((inv) => inv.goodsReceiptId.in(receiptIds)).aggregate((a) => ({ total: a.count() })),
  ]);

  return { items, meta: buildMeta(pagination, total) };
}

export async function getInvoiceById(companyId: string, id: string): Promise<InvoiceRow> {
  const invoice = await db.orm.public.Invoice.where((inv) => inv.id.eq(id)).first();
  if (!invoice) {
    throw new NotFoundError('Invoice not found');
  }
  // Company-scoping goes through the goods receipt (Invoice has no companyId of its own).
  await getGoodsReceiptById(companyId, invoice.goodsReceiptId);
  return invoice;
}
