import { Router } from 'express';
import { validateQuery } from '../../shared/validate';
import { paginationQuerySchema } from '../../shared/pagination';
import * as controller from './invoice.controller';

export const invoiceRouter = Router();

/**
 * @openapi
 * /procurement/invoices:
 *   get:
 *     tags: [Procurement]
 *     summary: List invoices (read-only — always auto-generated by a goods receipt)
 *     security: [{ bearerAuth: [] }]
 *     parameters: [{ $ref: '#/components/parameters/PageParam' }, { $ref: '#/components/parameters/PageSizeParam' }]
 *     responses:
 *       200: { description: OK, content: { application/json: { schema: { type: object, properties: { data: { type: array, items: { $ref: '#/components/schemas/Invoice' } }, meta: { $ref: '#/components/schemas/PaginationMeta' } } } } } }
 *       401: { $ref: '#/components/responses/Unauthorized' }
 */
invoiceRouter.get('/', validateQuery(paginationQuerySchema), controller.list);

/**
 * @openapi
 * /procurement/invoices/{id}:
 *   get:
 *     tags: [Procurement]
 *     summary: Get an invoice by id (read-only)
 *     security: [{ bearerAuth: [] }]
 *     parameters: [{ $ref: '#/components/parameters/IdParam' }]
 *     responses:
 *       200: { description: OK, content: { application/json: { schema: { type: object, properties: { data: { $ref: '#/components/schemas/Invoice' } } } } } }
 *       401: { $ref: '#/components/responses/Unauthorized' }
 *       404: { $ref: '#/components/responses/NotFound' }
 */
invoiceRouter.get('/:id', controller.getById);
