#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/0155049009fa95e56a30af8a4c28aad54fba4d07a096518234dde070edb67e12/contract';
import endContract from '../../snapshots/0155049009fa95e56a30af8a4c28aad54fba4d07a096518234dde070edb67e12/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'company',
        columns: [
          col('address', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('city', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('country', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'externalSystem',
        columns: [
          col('apiKeyHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('apiSecretHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'goodsReceipt',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdBy', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('purchaseOrderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('receivedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('supplierId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('warehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'goodsReceipt_status_check_464f1b9c',
            "\"status\" IN ('PARTIALLY_RECEIVED', 'RECEIVED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'goodsReceiptItem',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('receiptId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('unitCost', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('goodsReceiptItem_status_check_856bfb63', '"status" IN (\'RECEIVED\')'),
          checkExpression('receipt_item_quantity_positive_fc510296', '"quantity" > 0'),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'invoice',
        columns: [
          col('amount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('goodsReceiptId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('invoiceNumber', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issuedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'item',
        columns: [
          col('baseUnitId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('categoryId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isBuyable', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('isStockable', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reorderThreshold', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'itemCategory',
        columns: [
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'nomenclature',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('version', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'nomenclatureLine',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('nomenclatureId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('subItemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('unitId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'purchaseOrder',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdBy', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('expectedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('supplierId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('warehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'purchaseOrder_status_check_05be86bb',
            "\"status\" IN ('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'purchaseOrderItem',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('purchaseOrderId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('unitCost', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('po_item_quantity_positive_fc510296', '"quantity" > 0'),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'stockLevel',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('warehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'stockMovement',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdBy', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('nomenclatureId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('receiptItemId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('transferItemId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('warehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'movement_at_most_one_source_4193fe3e',
            '((("nomenclatureId" IS NOT NULL)::int + ("receiptItemId" IS NOT NULL)::int + ("transferItemId" IS NOT NULL)::int) <= 1)',
          ),
          checkExpression('movement_quantity_positive_fc510296', '"quantity" > 0'),
          checkExpression(
            'movement_reason_only_for_manual_out_1177da92',
            '(("type" = \'MANUAL_OUT\') = ("reason" IS NOT NULL))',
          ),
          checkExpression(
            'stockMovement_reason_check_3cca4062',
            "\"reason\" IN ('WASTE', 'SPOILAGE', 'INTERNAL_USE', 'THEFT', 'OTHER')",
          ),
          checkExpression(
            'stockMovement_type_check_a6d21566',
            "\"type\" IN ('STOCK_IN', 'CONSUMPTION', 'MANUAL_OUT', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUSTMENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'supplier',
        columns: [
          col('address', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('city', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('country', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('supplier_type_check_1846b4f7', "\"type\" IN ('COMPANY', 'INDIVIDUAL')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'unit',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('factorToBase', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('family', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isBase', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('symbol', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('unit_family_check_5839663e', "\"family\" IN ('MASS', 'VOLUME', 'UNIT')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('employeeId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('firstName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['employeeId']),
          checkExpression('user_role_check_58a5b3c0', "\"role\" IN ('Admin', 'Manager', 'Staff')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'warehouse',
        columns: [
          col('companyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deletedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'warehouseTransfer',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('createdBy', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('fromWarehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('toWarehouseId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'transfer_distinct_warehouses_391332e4',
            '"fromWarehouseId" <> "toWarehouseId"',
          ),
          checkExpression(
            'warehouseTransfer_status_check_e235185f',
            "\"status\" IN ('PENDING', 'DISPATCHED', 'RECEIVED', 'DISCREPANCY')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'warehouseTransferItem',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('itemId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('transferId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('transfer_item_quantity_positive_fc510296', '"quantity" > 0'),
        ],
      }),
      this.addUnique({
        schema: 'public',
        table: 'externalSystem',
        constraint: 'externalSystem_apiKeyHash_key',
        columns: ['apiKeyHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'invoice',
        constraint: 'invoice_goodsReceiptId_key',
        columns: ['goodsReceiptId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'invoice',
        constraint: 'invoice_invoiceNumber_key',
        columns: ['invoiceNumber'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'nomenclature',
        constraint: 'nomenclature_itemId_version_key',
        columns: ['itemId', 'version'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'nomenclatureLine',
        constraint: 'nomenclatureLine_nomenclatureId_subItemId_key',
        columns: ['nomenclatureId', 'subItemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'purchaseOrderItem',
        constraint: 'purchaseOrderItem_purchaseOrderId_itemId_key',
        columns: ['purchaseOrderId', 'itemId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'stockLevel',
        constraint: 'stockLevel_itemId_warehouseId_key',
        columns: ['itemId', 'warehouseId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_companyId_email_key',
        columns: ['companyId', 'email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'warehouseTransferItem',
        constraint: 'warehouseTransferItem_transferId_itemId_key',
        columns: ['transferId', 'itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'externalSystem',
        index: 'externalSystem_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceipt',
        index: 'goodsReceipt_createdBy_idx_ba0f792f',
        columns: ['createdBy'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceipt',
        index: 'goodsReceipt_purchaseOrderId_idx_3e3a8c45',
        columns: ['purchaseOrderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceipt',
        index: 'goodsReceipt_supplierId_idx_c4d9a8b9',
        columns: ['supplierId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceipt',
        index: 'goodsReceipt_warehouseId_idx_8ff93e70',
        columns: ['warehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceiptItem',
        index: 'goodsReceiptItem_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'goodsReceiptItem',
        index: 'goodsReceiptItem_receiptId_idx_9b8e07be',
        columns: ['receiptId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'item',
        index: 'item_baseUnitId_idx_e973fd0f',
        columns: ['baseUnitId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'item',
        index: 'item_categoryId_idx_15c304f2',
        columns: ['categoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'item',
        index: 'item_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'itemCategory',
        index: 'itemCategory_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'nomenclature',
        index: 'nomenclature_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'nomenclature',
        index: 'nomenclature_one_active_per_item_2517e97f',
        columns: ['itemId'],
        extras: { where: '("isActive" = true AND "deletedAt" IS NULL)', unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'nomenclatureLine',
        index: 'nomenclatureLine_nomenclatureId_idx_2a228baa',
        columns: ['nomenclatureId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'nomenclatureLine',
        index: 'nomenclatureLine_subItemId_idx_59be4d34',
        columns: ['subItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'nomenclatureLine',
        index: 'nomenclatureLine_unitId_idx_be785412',
        columns: ['unitId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrder',
        index: 'purchaseOrder_createdBy_idx_ba0f792f',
        columns: ['createdBy'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrder',
        index: 'purchaseOrder_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrder',
        index: 'purchaseOrder_supplierId_idx_c4d9a8b9',
        columns: ['supplierId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrder',
        index: 'purchaseOrder_warehouseId_idx_8ff93e70',
        columns: ['warehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrderItem',
        index: 'purchaseOrderItem_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'purchaseOrderItem',
        index: 'purchaseOrderItem_purchaseOrderId_idx_3e3a8c45',
        columns: ['purchaseOrderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockLevel',
        index: 'stockLevel_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockLevel',
        index: 'stockLevel_warehouseId_idx_8ff93e70',
        columns: ['warehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_createdBy_idx_ba0f792f',
        columns: ['createdBy'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_itemId_warehouseId_idx_ea036965',
        columns: ['itemId', 'warehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_nomenclatureId_idx_2a228baa',
        columns: ['nomenclatureId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_receiptItemId_idx_7c567faf',
        columns: ['receiptItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_transferItemId_idx_88f4e095',
        columns: ['transferItemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_type_idx_b6b604ea',
        columns: ['type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stockMovement',
        index: 'stockMovement_warehouseId_idx_8ff93e70',
        columns: ['warehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier',
        index: 'supplier_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'unit',
        index: 'unit_one_base_per_family_9d26b17e',
        columns: ['family'],
        extras: { where: '("isBase" = true AND "deletedAt" IS NULL)', unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'user',
        index: 'user_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouse',
        index: 'warehouse_companyId_idx_33acc5ed',
        columns: ['companyId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransfer',
        index: 'warehouseTransfer_createdBy_idx_ba0f792f',
        columns: ['createdBy'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransfer',
        index: 'warehouseTransfer_fromWarehouseId_idx_4006b0b1',
        columns: ['fromWarehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransfer',
        index: 'warehouseTransfer_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransfer',
        index: 'warehouseTransfer_toWarehouseId_idx_f640a978',
        columns: ['toWarehouseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransferItem',
        index: 'warehouseTransferItem_itemId_idx_41357140',
        columns: ['itemId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'warehouseTransferItem',
        index: 'warehouseTransferItem_transferId_idx_2ecab561',
        columns: ['transferId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'externalSystem',
        foreignKey: {
          name: 'externalSystem_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceipt',
        foreignKey: {
          name: 'goodsReceipt_purchaseOrderId_fkey',
          columns: ['purchaseOrderId'],
          references: { schema: 'public', table: 'purchaseOrder', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceipt',
        foreignKey: {
          name: 'goodsReceipt_supplierId_fkey',
          columns: ['supplierId'],
          references: { schema: 'public', table: 'supplier', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceipt',
        foreignKey: {
          name: 'goodsReceipt_warehouseId_fkey',
          columns: ['warehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceipt',
        foreignKey: {
          name: 'goodsReceipt_createdBy_fkey',
          columns: ['createdBy'],
          references: { schema: 'public', table: 'user', columns: ['employeeId'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceiptItem',
        foreignKey: {
          name: 'goodsReceiptItem_receiptId_fkey',
          columns: ['receiptId'],
          references: { schema: 'public', table: 'goodsReceipt', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'goodsReceiptItem',
        foreignKey: {
          name: 'goodsReceiptItem_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'invoice',
        foreignKey: {
          name: 'invoice_goodsReceiptId_fkey',
          columns: ['goodsReceiptId'],
          references: { schema: 'public', table: 'goodsReceipt', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'item',
        foreignKey: {
          name: 'item_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'itemCategory', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'item',
        foreignKey: {
          name: 'item_baseUnitId_fkey',
          columns: ['baseUnitId'],
          references: { schema: 'public', table: 'unit', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'item',
        foreignKey: {
          name: 'item_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'itemCategory',
        foreignKey: {
          name: 'itemCategory_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'nomenclature',
        foreignKey: {
          name: 'nomenclature_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'nomenclatureLine',
        foreignKey: {
          name: 'nomenclatureLine_nomenclatureId_fkey',
          columns: ['nomenclatureId'],
          references: { schema: 'public', table: 'nomenclature', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'nomenclatureLine',
        foreignKey: {
          name: 'nomenclatureLine_subItemId_fkey',
          columns: ['subItemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'nomenclatureLine',
        foreignKey: {
          name: 'nomenclatureLine_unitId_fkey',
          columns: ['unitId'],
          references: { schema: 'public', table: 'unit', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchaseOrder',
        foreignKey: {
          name: 'purchaseOrder_supplierId_fkey',
          columns: ['supplierId'],
          references: { schema: 'public', table: 'supplier', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchaseOrder',
        foreignKey: {
          name: 'purchaseOrder_warehouseId_fkey',
          columns: ['warehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchaseOrder',
        foreignKey: {
          name: 'purchaseOrder_createdBy_fkey',
          columns: ['createdBy'],
          references: { schema: 'public', table: 'user', columns: ['employeeId'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchaseOrderItem',
        foreignKey: {
          name: 'purchaseOrderItem_purchaseOrderId_fkey',
          columns: ['purchaseOrderId'],
          references: { schema: 'public', table: 'purchaseOrder', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'purchaseOrderItem',
        foreignKey: {
          name: 'purchaseOrderItem_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockLevel',
        foreignKey: {
          name: 'stockLevel_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockLevel',
        foreignKey: {
          name: 'stockLevel_warehouseId_fkey',
          columns: ['warehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_warehouseId_fkey',
          columns: ['warehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_nomenclatureId_fkey',
          columns: ['nomenclatureId'],
          references: { schema: 'public', table: 'nomenclature', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_receiptItemId_fkey',
          columns: ['receiptItemId'],
          references: { schema: 'public', table: 'goodsReceiptItem', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_transferItemId_fkey',
          columns: ['transferItemId'],
          references: { schema: 'public', table: 'warehouseTransferItem', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stockMovement',
        foreignKey: {
          name: 'stockMovement_createdBy_fkey',
          columns: ['createdBy'],
          references: { schema: 'public', table: 'user', columns: ['employeeId'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'supplier',
        foreignKey: {
          name: 'supplier_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'user',
        foreignKey: {
          name: 'user_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouse',
        foreignKey: {
          name: 'warehouse_companyId_fkey',
          columns: ['companyId'],
          references: { schema: 'public', table: 'company', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouseTransfer',
        foreignKey: {
          name: 'warehouseTransfer_fromWarehouseId_fkey',
          columns: ['fromWarehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouseTransfer',
        foreignKey: {
          name: 'warehouseTransfer_toWarehouseId_fkey',
          columns: ['toWarehouseId'],
          references: { schema: 'public', table: 'warehouse', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouseTransfer',
        foreignKey: {
          name: 'warehouseTransfer_createdBy_fkey',
          columns: ['createdBy'],
          references: { schema: 'public', table: 'user', columns: ['employeeId'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouseTransferItem',
        foreignKey: {
          name: 'warehouseTransferItem_transferId_fkey',
          columns: ['transferId'],
          references: { schema: 'public', table: 'warehouseTransfer', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'warehouseTransferItem',
        foreignKey: {
          name: 'warehouseTransferItem_itemId_fkey',
          columns: ['itemId'],
          references: { schema: 'public', table: 'item', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'company' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'externalSystem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'goodsReceipt' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'goodsReceiptItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'invoice' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'item' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'itemCategory' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'nomenclature' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'nomenclatureLine' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'purchaseOrder' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'purchaseOrderItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'stockLevel' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'stockMovement' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'supplier' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'unit' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'user' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'warehouse' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'warehouseTransfer' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'warehouseTransferItem' }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
